language: csharp
mono: none
dotnet: 3.0.100
script:
 - dotnet restore
 - dotnet build
 - cd ProductService.Test && dotnet test
 - cd ../PricingService.Test && dotnet test
 - cd ../PolicyService.Test && dotnet test
 - cd ../PaymentService.Test && dotnet test
